[build]
  publish = "site"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/post.html"
  to = "/post.html"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=60"
